Document: docker-manager
Title: Debian docker-manager Manual
Author: <insert document author here>
Abstract: This manual describes what docker-manager is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/docker-manager/docker-manager.sgml.gz

Format: postscript
Files: /usr/share/doc/docker-manager/docker-manager.ps.gz

Format: text
Files: /usr/share/doc/docker-manager/docker-manager.text.gz

Format: HTML
Index: /usr/share/doc/docker-manager/html/index.html
Files: /usr/share/doc/docker-manager/html/*.html
